version: '3.9'

x-common-variables: &common-variables
  HYPERCUBE_SIZE: 3
  SUPERSET_THRESHOLD: 10
  INIT_PORT: 8880

services:
  hypercube_0:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8880
  hypercube_1:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8881
  hypercube_2:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8882
  hypercube_3:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8883
  hypercube_4:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8884
  hypercube_5:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8885
  hypercube_6:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8886
  hypercube_7:
    network_mode: 'host'
    image: hypercube:latest
    environment:
      <<: *common-variables
      NODE_PORT: 8887
  hypercube-client:
    network_mode: 'host'
    image: hypercube-client:latest
    environment:
      <<: *common-variables
  hypercube-client-tracing:
    network_mode: 'host'
    image: hypercube-client-tracing:latest
    environment:
      <<: *common-variables
      BLOCKCHAIN_ADDRESS: http://localhost:8545
      CHAIN_ID: 1337
    volumes:
      - ./data/client:/client_data
      - ./client-tracing/contracts:/client_data/contracts
      - ./client-tracing/objects:/client_data/objects
  ipfs:
    network_mode: 'host'
    image: ipfs/go-ipfs:v0.8.0
    environment:
      IPFS_PROFILE: server
      IPFS_PATH: /ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
  ganache:
    network_mode: 'host'
    image: trufflesuite/ganache-cli:latest
    volumes:
      - ./data/ganache:/ganache_data
    command: --seed 42 --db=/ganache_data